Set SystemSet = GetObject("winmgmts:").InstancesOf ("Win32_ComputerSystem")

for each System in SystemSet
	WScript.Echo AdminPasswordStatus
	WScript.Echo AutomaticManagedPagefile
	WScript.Echo AutomaticResetBootOption
	WScript.Echo AutomaticResetCapability
	WScript.Echo BootOptionOnLimit
	WScript.Echo BootOptionOnWatchDog
	WScript.Echo BootROMSupported
	WScript.Echo BootupState
	WScript.Echo BootStatus[]
	WScript.Echo Caption
	WScript.Echo ChassisBootupState
	WScript.Echo ChassisSKUNumber
	WScript.Echo CreationClassName
	WScript.Echo CurrentTimeZone
	WScript.Echo DaylightInEffect
	WScript.Echo Description
	WScript.Echo DNSHostName
	WScript.Echo Domain
	WScript.Echo DomainRole
	WScript.Echo EnableDaylightSavingsTime
	WScript.Echo FrontPanelResetStatus
	WScript.Echo HypervisorPresent
	WScript.Echo InfraredSupported
	WScript.Echo InitialLoadInfo[]
	WScript.Echo InstallDate
	WScript.Echo KeyboardPasswordStatus
	WScript.Echo LastLoadInfo
	WScript.Echo Manufacturer
	WScript.Echo Model
	WScript.Echo Name
	WScript.Echo NameFormat
	WScript.Echo NetworkServerModeEnabled
	WScript.Echo NumberOfLogicalProcessors
	WScript.Echo NumberOfProcessors
	WScript.Echo OEMLogoBitmap[]
	WScript.Echo OEMStringArray[]
	WScript.Echo PartOfDomain
	WScript.Echo PauseAfterReset
	WScript.Echo PCSystemType
	WScript.Echo PCSystemTypeEx
	WScript.Echo PowerManagementCapabilities[]
	WScript.Echo PowerManagementSupported
	WScript.Echo PowerOnPasswordStatus
	WScript.Echo PowerState
	WScript.Echo PowerSupplyState
	WScript.Echo PrimaryOwnerContact
	WScript.Echo PrimaryOwnerName
	WScript.Echo ResetCapability
	WScript.Echo ResetCount
	WScript.Echo ResetLimit
	WScript.Echo Roles[]
	WScript.Echo Status
	WScript.Echo SupportContactDescription[]
	WScript.Echo SystemFamily
	WScript.Echo SystemSKUNumber
	WScript.Echo SystemStartupDelay
	WScript.Echo SystemStartupOptions[]
	WScript.Echo SystemStartupSetting
	WScript.Echo SystemType
	WScript.Echo ThermalState
	WScript.Echo TotalPhysicalMemory
	WScript.Echo UserName
	WScript.Echo WakeUpType
	WScript.Echo Workgroup
next

